### ISSUE TITLE
Missing dependencies in knip-sdk-nightly-full.target

### ISSUE THREAD

**Issue by Squareys** [knime-ip/knip-sdk-setup#12]
Hi @gab1one !

I just tried using the full nightly target, but it seems as if it cannot find `com.knime.features.workbench.repository.custom.feature.group`. When setting as target platform anyway, it suddenly complains about every single plugin not being found.

Do you have an idea what could be causing this?

Thanks in advance, 
Jonathan

**Comment by gab1one** [comment]
Thank you for findig this. That commit fixed it for me:
https://github.com/knime-ip/knip-sdk-setup/commit/b5f252a2798a42b29052bc88c04105ff3ac4d1d1
If you are missing any functionality in the target plattfrom tell me.

**Comment by Squareys** [comment]
Thanks! :+1:
